# Generated by Django 2.2.1 on 2019-05-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='upload')),
                ('base_64', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(max_length=100)),
                ('pet_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
