# Generated by Django 2.2.1 on 2019-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='votes_up',
            field=models.IntegerField(default=0),
        ),
    ]
