# Generated by Django 2.2.1 on 2019-05-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_post_total_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-total_votes'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
